name: Django CI

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
            DJANGO_SETTINGS_MODULE: config.settings
            PYTHONUNBUFFERED: 1

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Clear Python cache
              run: |
                  sudo rm -rf ~/.cache/pip
                  sudo rm -rf ~/.pyenv

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m venv venv
                  source venv/bin/activate
                  pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run migrations
              env:
                  POSTGRES_DB: test_db
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_HOST: 127.0.0.1
                  POSTGRES_PORT: 5432
                  DJANGO_SETTINGS_MODULE: config.settings
                  SECRET_KEY: testsecretkey
              run: |
                  source venv/bin/activate
                  python manage.py migrate

            - name: Run tests
              env:
                  POSTGRES_DB: test_db
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_HOST: 127.0.0.1
                  POSTGRES_PORT: 5432
                  DJANGO_SETTINGS_MODULE: config.settings
                  SECRET_KEY: testsecretkey
              run: |
                  source venv/bin/activate
                  python manage.py test

            - name: Run linters (flake8)
              run: |
                  source venv/bin/activate
                  pip install flake8
                  flake8 .

            - name: Check code formatting (Black)
              run: |
                  source venv/bin/activate
                  pip install black
                  black --check .

            - name: Check imports formatting (isort)
              run: |
                  source venv/bin/activate
                  pip install isort
                  isort --check-only .
